---
- name: Setup .bashrc
  tags: bashrc
  ansible.builtin.get_url:
    url: '{{ bashrc_url | mandatory }}'
    dest: "{{ sb_dest | default(lookup('env', 'HOME') + '/.bashrc') }}"
    owner: '{{ sb_user | mandatory }}'
    mode: '0644'
    force: true
