- name: Setup .bashrc
  tags: bashrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hi917/dotfiles/master/.bashrc
    dest: '{{ dest | default("/home/" + username) }}'
    owner: '{{ username }}'
    mode: '0644'
