- name: Setup .bashrc
  tags: bashrc
  ansible.builtin.get_url:
    url: '{{ bashrc_url }}'
    dest: '{{ sb_dest | default("/home/" + sb_user ) }}/.bashrc'
    owner: '{{ sb_user }}'
    mode: '0644'
    force: true
