- name: Create user
  tags: user
  ansible.builtin.user:
    name: '{{ username }}'
    password: '{{ password }}'
    state: present
    shell: /bin/bash
    group: '{{ group }}'
    home: '/home/{{ username }}'
    create_home: true
