- name: Create user
  tags: user
  become: true
  ansible.builtin.user:
    name: '{{ cu_name }}'
    password: '{{ cu_password | default(default_user_password) }}'
    state: present
    shell: /bin/bash
    group: '{{ cu_group | default("") }}'
    home: '/home/{{ cu_name }}'
    create_home: true

- name: Ensure user is sudoer with no password required
  tags: sudo
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ cu_name }} ALL\='
    line: '{{ cu_name }} ALL=(ALL) NOPASSWD:ALL'
    state: present
  when: 'cu_group == "sudo"'
