- name: Setup WOL
  when: "'pve_nodes' in group_names"

  block:
  - name: Install ethtool
    tags: ethtool
    ansible.builtin.apt:
      name: ethtool
      state: present

  - name: Check interface
    tags: wol
    ansible.builtin.shell:
      cmd: ethtool {{ sw_interface }} | grep 'Wake-on' | tail -1 | awk '{print substr($0,length,1)}'
    register: wol_enabled
    changed_when: false

  - name: Current interface
    tags: wol
    ansible.builtin.debug:
      msg: 'Current status is: {{ wol_enabled.stdout }}'

  - name: Set interface
    tags: wol
    ansible.builtin.command:
      cmd: ethtool -s {{ sw_interface }} wol {{ sw_value }}
    when: 'value != wol_enabled.stdout'
    changed_when: 'value != wol_enabled.stdout'

  - name: Template out wol.service
    tags: wol, wol.service
    ansible.builtin.template:
      src: wol.service.j2
      dest: /etc/systemd/system/wol.service
      owner: root
      mode: '0644'

  - name: Start wol.service
    tags: wol, wol.service
    ansible.builtin.systemd:
      name: wol.service
      enabled: true
      state: started
    changed_when: false
