---
- name: Setup WOL on metal
  when: "'pve_nodes' in group_names"
  become: true
  tags: wol

  block:
  - name: Check interface
    register: wol_enabled
    changed_when: false
    ansible.builtin.shell:
      cmd: /usr/sbin/ethtool {{ interface }} | grep 'Wake-on' | tail -1 | awk '{print substr($0,length,1)}'

  - name: Current interface
    ansible.builtin.debug:
      msg: 'Current status is: {{ wol_enabled["stdout"] }}'

  - name: Set interface
    when: wol_value != wol_enabled['stdout']
    changed_when: wol_value != wol_enabled['stdout']
    ansible.builtin.command:
      cmd: /usr/sbin/ethtool -s {{ interface }} wol {{ wol_value }}

  - name: Template out wol.service
    tags: wol.service
    ansible.builtin.template:
      src: wol.service.j2
      dest: /etc/systemd/system/wol.service
      owner: root
      mode: '0644'

  - name: Start wol.service
    changed_when: false
    tags: wol.service
    ansible.builtin.systemd:
      name: wol.service
      enabled: true
      state: started
