---
- name: Setup VIM with .vimrc
  tags: vimrc

  block:
  - name: Download .vimrc
    ansible.builtin.get_url:
      url: '{{ vimrc_url | mandatory }}'
      dest: "{{ sv_dest | default(lookup('env', 'HOME') + '/.vimrc') }}"
      owner: '{{ sv_user | mandatory }}'
      mode: '0644'
      force: true

  - name: Run VIM Plug PlugInstall
    failed_when: 1 == 0
    changed_when: false
    tags: vimplug
    ansible.builtin.command:
      cmd: "vim -E +PlugInstall +qa"
