---
- name: Setup VIM with .vimrc
  tags: vimrc

  block:
  - name: Download .vimrc
    ansible.builtin.get_url:
      url: '{{ vimrc_url | mandatory }}'
      dest: "{{ sv_dest | default(lookup('env', 'HOME') + '/.vimrc') }}"
      owner: '{{ sv_user | mandatory }}'
      mode: '0644'
      force: true

  - name: Run VIM Plug PlugInstall
    failed_when: 1 == 0
    changed_when: false
    tags: vimplug
    become_user: '{{ sv_user | mandatory }}'
    ansible.builtin.command:
      cmd: "vim -u {{ lookup('env', 'HOME') + '/.vimrc' }} -E -s  +\"PlugInstall --sync\" +qa"

  - name: Ensure VIM plugins installed
    register: plugged
    failed_when: plugged.stat.isdir is not defined or not plugged.stat.isdir
    tags: vimplug
    ansible.builtin.stat:
      path: "{{ lookup('env', 'HOME') + '/.vim/plugged' }}"
