- name: Ensure VIM and cURL
  tags: vim, curl
  ansible.builtin.apt:
    name: 
      - vim
      - curl
    state: present

- name: Download .vimrc
  tags: vimrc
  ansible.builtin.get_url:
    url: '{{ vimrc_url }}'
    dest: '{{ sv_dest | default("/home/" + sv_user) }}/.vimrc'
    owner: '{{ sv_user }}'
    mode: '0644'
    force: true

- name: Run VIM Plug PlugInstall
  tags: vimrc, vimplug, last
  ansible.builtin.command:
    cmd: "vim -E +PlugInstall +qa"
  failed_when: 1 == 0
  changed_when: false
