---
- name: Standard APT
  become: true
  tags: apt

  block:
  - name: Update packages (apt-get upgrade)
    ansible.builtin.apt:
      update_cache: true

  - name: Upgrade packages (apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: true

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: true

  - name: Install packages
    tags: apt_packages
    when:
      - packages is defined
      - packages is iterable
      - packages | length > 0
    ansible.builtin.apt:
      name: '{{ packages }}'
      state: present
